# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # ZKsync uses `tracing` to generate logs, which doesn't populate timestamps.
  # However, Quickwit ignores logs that have no timestamp, so we force set it.
  transform/set_time_unix_nano:
    log_statements:
      - context: log
        statements:
          - set(time_unix_nano, observed_time_unix_nano)
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/quickwit:
    endpoint: quickwit:7281
    tls:
      insecure: true  

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [batch, transform/set_time_unix_nano]
      exporters: [debug, otlp/quickwit]

  extensions: [health_check, pprof, zpages]
