apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: Quickwit
    type: quickwit-quickwit-datasource
    access: proxy
    orgId: 1
    url: http://quickwit:7280/api/v1
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      index: otel-logs-v0_7
      logMessageField: body.message
      logLevelField: severity_text

  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger-query:16686
    basicAuth: false
    isDefault: false
    editable: true
